### PR TITLE
migrate properties from south dakota entity sets

### PR DESCRIPTION
**Pull request by katherinebernstein**

### CODE REVIEW

**Review by makosblade — APPROVED** [review]
👍

**Review by katherinebernstein — COMMENTED** [review]
<approval>

**Review by katherinebernstein — COMMENTED** [review]
<approval>

**Review by katherinebernstein — COMMENTED** [review]
hello

**Review by makosblade — COMMENTED** [review]
<brahj>

**Review by katherinebernstein — COMMENTED** [review]
<invisible comment>

**Review by makosblade — COMMENTED** [review]
<iHaveNoMouthButiMustScream>

**Pull request merged**
