### PR TITLE
no more ghosts

### PR DESCRIPTION
**Pull request by katherinebernstein**

### CODE REVIEW

**Review by you-leee — APPROVED** [review]

**Comment by katherinebernstein** [comment]
Update: I meant to block the ghosts but I actually just let them all out into the city and caused chaos

**Comment by makosblade** [comment]
> Update: I meant to block the ghosts but I actually just let them all out into the city and caused chaos

u wot m8?

**Comment by katherinebernstein** [comment]
ghostbusters-tv-spot-we-catch-ghosts

**Comment by makosblade** [comment]
who-let-the-ghosts-out

**Pull request merged**
